export type AccessKey =
  | "IDENT_NAME" | "IDENT_NID" | "IDENT_BIRTHDATE" | "IDENT_SEX" | "IDENT_ADDRESS" | "IDENT_PHONE"
  | "VL" | "VL_DATE"
  | "CD4_ABS" | "CD4_PCT"
  | "ART_START" | "ART_START_HF" | "ART_START_PREG" | "ART_START_WHO"
  | "ARV_LAST_PICKUP" | "ARV_LAST_REGIMEN" | "ARV_NEXT_PICKUP"
  | "LINE_1_ALT" | "LINE_2_CHANGE" | "LINE_3_CHANGE"
  | "TB_GENEXPERT" | "TB_BACILOSCOPIA" | "TB_LAM"
  | "LAB_HGB" | "LAB_AST" | "LAB_ALT" | "LAB_AMI" | "LAB_GLC" | "LAB_PCR"
  | "TPT" | "TPT_START" | "TPT_END" | "TPT_LAST_PICKUP" | "TPT_PICKUP_TYPE"
  | "CTZ_START" | "CTZ_END"
  | "VIA" | "HPV_DNA"
  | "HF"
  | "CONSULT_LAST" | "CONSULT_NEXT"
  | "ANTROP_WEIGHT" | "ANTROP_HEIGHT" | "ANTROP_BMI"
  | "DSD"
  | "WHO_STAGE"
  | "PROV_PREG_AT_LAST" | "PROV_BF_AT_LAST" | "PROV_LAST_STATE"
  | "CONF_NAME" | "CONF_PHONE";

export const PROFILE_ACCESS = {
  APSS: [
    "IDENT_NAME","IDENT_NID","IDENT_BIRTHDATE","IDENT_SEX","IDENT_ADDRESS","IDENT_PHONE",
    "VL","VL_DATE","CD4_ABS","CD4_PCT",
    "ART_START","ART_START_HF","ART_START_PREG","ART_START_WHO",
    "ARV_LAST_PICKUP","ARV_LAST_REGIMEN","ARV_NEXT_PICKUP",
    "LINE_1_ALT","LINE_2_CHANGE","LINE_3_CHANGE",
    "TB_GENEXPERT","TB_BACILOSCOPIA","TB_LAM",
    "TPT","TPT_START","TPT_END","TPT_LAST_PICKUP","TPT_PICKUP_TYPE",
    "VIA","HF","CONSULT_LAST","CONSULT_NEXT",
    "ANTROP_WEIGHT","ANTROP_HEIGHT","ANTROP_BMI","DSD",
    "PROV_PREG_AT_LAST","PROV_BF_AT_LAST","CONF_NAME","CONF_PHONE"
  ],
  ATS: ["IDENT_NAME","IDENT_NID","IDENT_BIRTHDATE","IDENT_SEX","IDENT_ADDRESS","IDENT_PHONE","ARV_NEXT_PICKUP","HF"],
  FARMACIA: [
    "IDENT_NAME","IDENT_NID","IDENT_BIRTHDATE","IDENT_SEX","IDENT_ADDRESS","IDENT_PHONE",
    "VL","VL_DATE",
    "ART_START","ART_START_HF","ART_START_PREG","ART_START_WHO",
    "ARV_LAST_PICKUP","ARV_LAST_REGIMEN","ARV_NEXT_PICKUP",
    "LINE_1_ALT","LINE_2_CHANGE","LINE_3_CHANGE",
    "TPT","TPT_START","TPT_END","TPT_LAST_PICKUP","TPT_PICKUP_TYPE",
    "CTZ_START","CTZ_END","VIA","HF","CONSULT_LAST","CONSULT_NEXT",
    "ANTROP_WEIGHT","ANTROP_HEIGHT","ANTROP_BMI","DSD",
    "PROV_PREG_AT_LAST","PROV_BF_AT_LAST"
  ],
  LAB: [
    "IDENT_NAME","IDENT_NID","IDENT_BIRTHDATE","IDENT_SEX","IDENT_ADDRESS","IDENT_PHONE",
    "VL","VL_DATE","CD4_ABS","CD4_PCT","ARV_NEXT_PICKUP"
  ],
  PROVEDOR: [
    "IDENT_NAME","IDENT_NID","IDENT_BIRTHDATE","IDENT_SEX","IDENT_ADDRESS","IDENT_PHONE",
    "VL","VL_DATE","CD4_ABS","CD4_PCT",
    "ART_START","ART_START_HF","ART_START_PREG","ART_START_WHO",
    "ARV_LAST_PICKUP","ARV_LAST_REGIMEN","ARV_NEXT_PICKUP",
    "LINE_1_ALT","LINE_2_CHANGE","LINE_3_CHANGE",
    "TB_GENEXPERT","TB_BACILOSCOPIA","TB_LAM",
    "LAB_HGB","LAB_AST","LAB_ALT","LAB_AMI","LAB_GLC","LAB_PCR",
    "TPT","TPT_START","TPT_END","TPT_LAST_PICKUP","TPT_PICKUP_TYPE",
    "CTZ_START","CTZ_END","VIA","HPV_DNA","HF",
    "CONSULT_LAST","CONSULT_NEXT","ANTROP_WEIGHT","ANTROP_HEIGHT","ANTROP_BMI",
    "DSD","WHO_STAGE","PROV_PREG_AT_LAST","PROV_BF_AT_LAST","PROV_LAST_STATE",
    "CONF_NAME","CONF_PHONE"
  ],
} as const;
